name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 当代码推送到main分支时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # 检出你的代码库

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        # 登录到Docker Hub

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: v6ole/speedtest-chinese:latest
          labels: "org.opencontainers.image.source=${{ github.repositoryUrl }}"
        # 构建镜像并以 "v6ole/speedtest-chinese:latest" 为标签推送到仓库 